21-01-05 13:10:45-08  |Portal| Loading c:\muddev\evennia\evennia\server\portal\portal.py...
21-01-05 13:10:46-08  |Portal| Loaded.
21-01-05 13:10:46-08  |Portal| twistd 19.10.0 (c:\muddev\evenv\scripts\python.exe 3.7.0) starting up.
21-01-05 13:10:46-08  |Portal| reactor class: twisted.internet.selectreactor.SelectReactor.
21-01-05 13:10:46-08  |Portal| AMP starting on 4006
21-01-05 13:10:46-08  |Portal| Telnet starting on 4000
21-01-05 13:10:46-08  |Portal| Websocket starting on 4002
21-01-05 13:10:46-08  |Portal| Webserver-proxy starting on 4001
21-01-05 13:10:46-08  |Portal| Portal starting server ... ['c:\\muddev\\evennia\\evennia\\server\\twistd.bat', '--python=c:\\muddev\\evennia\\evennia\\server\\server.py']
21-01-05 13:11:55-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64908)
21-01-05 13:11:55-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64906)
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 579, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 649, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 87, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 286, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1079, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| [::] NoneType: None
21-01-05 13:13:31-08  |Portal| [EE] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
21-01-05 13:13:31-08  |Portal| [EE] ]
21-01-05 13:13:31-08  |Portal| [EE] Caught errback in webserver.py:75.
21-01-05 13:13:31-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\application\app.py", line 312, in runReactorWithLogging
	    reactor.run()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\base.py", line 1283, in run
	    self.mainLoop()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\base.py", line 1295, in mainLoop
	    self.doIteration(t)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 143, in doSelect
	    _logrun(selectable, _drdw, selectable, method)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, method=="doRead")
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\posixbase.py", line 252, in _disconnectSelectable
	    selectable.readConnectionLost(f)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 307, in readConnectionLost
	    self.connectionLost(reason)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 519, in connectionLost
	    self._commonConnection.connectionLost(self, reason)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 601, in connectionLost
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 87, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 286, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1079, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
21-01-05 13:13:31-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 579, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 649, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 87, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 286, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1079, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
21-01-05 13:14:11-08  |Portal| (TCP Port 4001 Closed)
21-01-05 13:14:11-08  |Portal| (TCP Port 4002 Closed)
21-01-05 13:14:11-08  |Portal| (TCP Port 4000 Closed)
21-01-05 13:14:11-08  |Portal| (TCP Port 4006 Closed)
21-01-05 13:14:11-08  |Portal| Main loop terminated.
21-01-05 13:14:11-08  |Portal| Server Shut Down.
21-01-05 13:14:11-08  |Portal| Server Shut Down.
