22-01-15 14:53:34-08  |Portal| Loading c:\muddev\evennia\evennia\server\portal\portal.py...
22-01-15 14:53:35-08  |Portal| Loaded.
22-01-15 14:53:35-08  |Portal| twistd 21.7.0 (c:\muddev\evenv\scripts\python.exe 3.7.0) starting up.
22-01-15 14:53:35-08  |Portal| reactor class: twisted.internet.selectreactor.SelectReactor.
22-01-15 14:53:35-08  |Portal| AMP starting on 4006
22-01-15 14:53:35-08  |Portal| Telnet starting on 4000
22-01-15 14:53:35-08  |Portal| Websocket starting on 4002
22-01-15 14:53:35-08  |Portal| Webserver-proxy starting on 4001
22-01-15 14:53:36-08  |Portal| Portal starting server ... 
22-01-15 14:54:38-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=62632)
22-01-15 14:54:38-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=62634)
22-01-15 14:54:38-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=62639)
22-01-15 14:54:38-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=62638)
22-01-15 14:54:38-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=62640)
22-01-15 14:54:38-08  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=62636)
22-01-15 14:55:00-08  |Portal| Portal starting server ... 
22-01-15 15:00:59-08  |Portal| (TCP Port 4001 Closed)
22-01-15 15:00:59-08  |Portal| (TCP Port 4000 Closed)
22-01-15 15:00:59-08  |Portal| (TCP Port 4006 Closed)
22-01-15 15:00:59-08  |Portal| (TCP Port 4002 Closed)
22-01-15 15:00:59-08  |Portal| Main loop terminated.
22-01-15 15:00:59-08  |Portal| Server Shut Down.
22-01-15 15:00:59-08  |Portal| Server Shut Down.
22-01-16 04:15:58-08  |Portal| Loading c:\muddev\evennia\evennia\server\portal\portal.py...
22-01-16 04:15:59-08  |Portal| Loaded.
22-01-16 04:15:59-08  |Portal| twistd 21.7.0 (c:\muddev\evenv\scripts\python.exe 3.7.0) starting up.
22-01-16 04:15:59-08  |Portal| reactor class: twisted.internet.selectreactor.SelectReactor.
22-01-16 04:15:59-08  |Portal| AMP starting on 4006
22-01-16 04:15:59-08  |Portal| Telnet starting on 4000
22-01-16 04:15:59-08  |Portal| Websocket starting on 4002
22-01-16 04:15:59-08  |Portal| Webserver-proxy starting on 4001
22-01-16 04:15:59-08  |Portal| Portal starting server ... 
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:13-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:14-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:16:14-08  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1132, in finish
	    "Request.finish called on a request after its connection was lost; "
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
22-01-16 04:21:56-08  |Portal| Portal starting server ... 
22-01-16 04:22:22-08  |Portal| Portal starting server ... 
22-01-16 04:23:58-08  |Portal| Portal starting server ... 
22-01-16 04:24:27-08  |Portal| Portal starting server ... 
22-01-16 04:25:48-08  |Portal| Portal starting server ... 
22-01-16 04:27:00-08  |Portal| Portal starting server ... 
22-01-16 04:34:24-08  |Portal| Portal starting server ... 
22-01-16 04:36:45-08  |Portal| Portal starting server ... 
22-01-16 12:30:32-08  |Portal| Portal starting server ... 
22-01-16 12:33:51-08  |Portal| Portal starting server ... 
22-01-16 12:34:12-08  |Portal| Portal starting server ... 
22-01-16 12:35:58-08  |Portal| Portal starting server ... 
22-01-16 12:37:16-08  |Portal| Portal starting server ... 
22-01-16 12:40:07-08  |Portal| Portal starting server ... 
22-01-16 12:45:01-08  |Portal| Portal starting server ... 
22-01-16 12:45:42-08  |Portal| Portal starting server ... 
22-01-16 12:47:51-08  |Portal| Portal starting server ... 
22-01-16 12:50:52-08  |Portal| Portal starting server ... 
22-01-16 12:51:17-08  |Portal| Portal starting server ... 
22-01-16 12:51:51-08  |Portal| Portal starting server ... 
22-01-16 12:55:04-08  |Portal| Portal starting server ... 
22-01-16 12:55:36-08  |Portal| Portal starting server ... 
22-01-16 12:56:45-08  |Portal| Portal starting server ... 
22-01-16 12:59:23-08  |Portal| Portal starting server ... 
22-01-16 12:59:49-08  |Portal| Portal starting server ... 
22-01-16 13:02:58-08  |Portal| Portal starting server ... 
22-01-16 13:09:04-08  |Portal| Portal starting server ... 
22-01-16 13:12:01-08  |Portal| Portal starting server ... 
22-01-16 13:12:52-08  |Portal| Portal starting server ... 
22-01-16 13:26:34-08  |Portal| Portal starting server ... 
22-01-16 13:27:37-08  |Portal| Portal starting server ... 
22-01-16 13:40:13-08  |Portal| Portal starting server ... 
22-01-16 13:46:53-08  |Portal| Portal starting server ... 
22-01-16 13:59:55-08  |Portal| Portal starting server ... 
22-01-16 14:02:53-08  |Portal| Portal starting server ... 
22-01-16 14:05:02-08  |Portal| Portal starting server ... 
22-01-16 14:06:36-08  |Portal| Portal starting server ... 
